<template>
    <div>
        <cardChartContent :cdata="chartData" />
    </div>
</template>

<script>
import cardChartContent from './chart.vue'
import { mapState } from 'vuex'
import axios from 'axios'
export default {
    name: 'cardChartContainer',
    components: {
        cardChartContent
    },
    data() {
        return {
            chartData: {
    "months": [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    ],
    "year": [
        "2016",
        "2017",
        "2018",
        "2019",
        "2020",
        "2021",
        "2022",
        "2023",
        "2024"
    ],
    "stardata": [
        [
            0,
            0,
            375
        ],
        [
            0,
            1,
            381
        ],
        [
            0,
            2,
            675
        ],
        [
            0,
            3,
            452
        ],
        [
            0,
            4,
            682
        ],
        [
            0,
            5,
            522
        ],
        [
            0,
            6,
            481
        ],
        [
            0,
            7,
            520
        ],
        [
            0,
            8,
            751
        ],
        [
            0,
            9,
            734
        ],
        [
            0,
            10,
            674
        ],
        [
            0,
            11,
            614
        ],
        [
            1,
            0,
            564
        ],
        [
            1,
            1,
            552
        ],
        [
            1,
            2,
            596
        ],
        [
            1,
            3,
            586
        ],
        [
            1,
            4,
            540
        ],
        [
            1,
            5,
            548
        ],
        [
            1,
            6,
            624
        ],
        [
            1,
            7,
            627
        ],
        [
            1,
            8,
            522
        ],
        [
            1,
            9,
            586
        ],
        [
            1,
            10,
            570
        ],
        [
            1,
            11,
            501
        ],
        [
            2,
            0,
            472
        ],
        [
            2,
            1,
            406
        ],
        [
            2,
            2,
            452
        ],
        [
            2,
            3,
            423
        ],
        [
            2,
            4,
            454
        ],
        [
            2,
            5,
            412
        ],
        [
            2,
            6,
            364
        ],
        [
            2,
            7,
            346
        ],
        [
            2,
            8,
            348
        ],
        [
            2,
            9,
            439
        ],
        [
            2,
            10,
            311
        ],
        [
            2,
            11,
            276
        ],
        [
            3,
            0,
            297
        ],
        [
            3,
            1,
            284
        ],
        [
            3,
            2,
            291
        ],
        [
            3,
            3,
            281
        ],
        [
            3,
            4,
            347
        ],
        [
            3,
            5,
            257
        ],
        [
            3,
            6,
            216
        ],
        [
            3,
            7,
            263
        ],
        [
            3,
            8,
            145
        ],
        [
            3,
            9,
            226
        ],
        [
            3,
            10,
            223
        ],
        [
            3,
            11,
            152
        ],
        [
            4,
            0,
            159
        ],
        [
            4,
            1,
            198
        ],
        [
            4,
            2,
            161
        ],
        [
            4,
            3,
            237
        ],
        [
            4,
            4,
            183
        ],
        [
            4,
            5,
            190
        ],
        [
            4,
            6,
            185
        ],
        [
            4,
            7,
            152
        ],
        [
            4,
            8,
            155
        ],
        [
            4,
            9,
            140
        ],
        [
            4,
            10,
            287
        ],
        [
            4,
            11,
            137
        ],
        [
            5,
            0,
            147
        ],
        [
            5,
            1,
            130
        ],
        [
            5,
            2,
            393
        ],
        [
            5,
            3,
            143
        ],
        [
            5,
            4,
            120
        ],
        [
            5,
            5,
            111
        ],
        [
            5,
            6,
            114
        ],
        [
            5,
            7,
            102
        ],
        [
            5,
            8,
            567
        ],
        [
            5,
            9,
            272
        ],
        [
            5,
            10,
            115
        ],
        [
            5,
            11,
            117
        ],
        [
            6,
            0,
            98
        ],
        [
            6,
            1,
            96
        ],
        [
            6,
            2,
            124
        ],
        [
            6,
            3,
            102
        ],
        [
            6,
            4,
            100
        ],
        [
            6,
            5,
            102
        ],
        [
            6,
            6,
            124
        ],
        [
            6,
            7,
            86
        ],
        [
            6,
            8,
            125
        ],
        [
            6,
            9,
            108
        ],
        [
            6,
            10,
            138
        ],
        [
            6,
            11,
            103
        ],
        [
            7,
            0,
            109
        ],
        [
            7,
            1,
            96
        ],
        [
            7,
            2,
            96
        ],
        [
            7,
            3,
            99
        ],
        [
            7,
            4,
            89
        ],
        [
            7,
            5,
            78
        ],
        [
            7,
            6,
            72
        ],
        [
            7,
            7,
            102
        ],
        [
            7,
            8,
            87
        ],
        [
            7,
            9,
            117
        ],
        [
            7,
            10,
            114
        ],
        [
            7,
            11,
            87
        ],
        [
            8,
            0,
            93
        ],
        [
            8,
            1,
            163
        ],
        [
            8,
            2,
            89
        ],
        [
            8,
            3,
            86
        ],
        [
            8,
            4,
            95
        ],
        [
            8,
            5,
            109
        ],
        [
            8,
            6,
            114
        ],
        [
            8,
            7,
            83
        ],
        [
            8,
            8,
            98
        ],
        [
            8,
            9,
            72
        ]
    ],
    "forkdata": [
        [
            0,
            0,
            38
        ],
        [
            0,
            1,
            64
        ],
        [
            0,
            2,
            90
        ],
        [
            0,
            3,
            93
        ],
        [
            0,
            4,
            160
        ],
        [
            0,
            5,
            132
        ],
        [
            0,
            6,
            137
        ],
        [
            0,
            7,
            152
        ],
        [
            0,
            8,
            185
        ],
        [
            0,
            9,
            203
        ],
        [
            0,
            10,
            209
        ],
        [
            0,
            11,
            219
        ],
        [
            1,
            0,
            175
        ],
        [
            1,
            1,
            167
        ],
        [
            1,
            2,
            195
        ],
        [
            1,
            3,
            214
        ],
        [
            1,
            4,
            201
        ],
        [
            1,
            5,
            193
        ],
        [
            1,
            6,
            167
        ],
        [
            1,
            7,
            187
        ],
        [
            1,
            8,
            204
        ],
        [
            1,
            9,
            202
        ],
        [
            1,
            10,
            168
        ],
        [
            1,
            11,
            176
        ],
        [
            2,
            0,
            187
        ],
        [
            2,
            1,
            164
        ],
        [
            2,
            2,
            165
        ],
        [
            2,
            3,
            144
        ],
        [
            2,
            4,
            166
        ],
        [
            2,
            5,
            141
        ],
        [
            2,
            6,
            128
        ],
        [
            2,
            7,
            151
        ],
        [
            2,
            8,
            115
        ],
        [
            2,
            9,
            156
        ],
        [
            2,
            10,
            128
        ],
        [
            2,
            11,
            111
        ],
        [
            3,
            0,
            124
        ],
        [
            3,
            1,
            119
        ],
        [
            3,
            2,
            121
        ],
        [
            3,
            3,
            112
        ],
        [
            3,
            4,
            118
        ],
        [
            3,
            5,
            99
        ],
        [
            3,
            6,
            138
        ],
        [
            3,
            7,
            98
        ],
        [
            3,
            8,
            103
        ],
        [
            3,
            9,
            90
        ],
        [
            3,
            10,
            106
        ],
        [
            3,
            11,
            86
        ],
        [
            4,
            0,
            86
        ],
        [
            4,
            1,
            78
        ],
        [
            4,
            2,
            103
        ],
        [
            4,
            3,
            110
        ],
        [
            4,
            4,
            97
        ],
        [
            4,
            5,
            85
        ],
        [
            4,
            6,
            79
        ],
        [
            4,
            7,
            55
        ],
        [
            4,
            8,
            65
        ],
        [
            4,
            9,
            81
        ],
        [
            4,
            10,
            60
        ],
        [
            4,
            11,
            71
        ],
        [
            5,
            0,
            64
        ],
        [
            5,
            1,
            58
        ],
        [
            5,
            2,
            83
        ],
        [
            5,
            3,
            63
        ],
        [
            5,
            4,
            71
        ],
        [
            5,
            5,
            57
        ],
        [
            5,
            6,
            62
        ],
        [
            5,
            7,
            62
        ],
        [
            5,
            8,
            53
        ],
        [
            5,
            9,
            58
        ],
        [
            5,
            10,
            58
        ],
        [
            5,
            11,
            69
        ],
        [
            6,
            0,
            42
        ],
        [
            6,
            1,
            83
        ],
        [
            6,
            2,
            92
        ],
        [
            6,
            3,
            55
        ],
        [
            6,
            4,
            58
        ],
        [
            6,
            5,
            63
        ],
        [
            6,
            6,
            54
        ],
        [
            6,
            7,
            60
        ],
        [
            6,
            8,
            47
        ],
        [
            6,
            9,
            31
        ],
        [
            6,
            10,
            48
        ],
        [
            6,
            11,
            42
        ],
        [
            7,
            0,
            57
        ],
        [
            7,
            1,
            59
        ],
        [
            7,
            2,
            53
        ],
        [
            7,
            3,
            43
        ],
        [
            7,
            4,
            35
        ],
        [
            7,
            5,
            31
        ],
        [
            7,
            6,
            38
        ],
        [
            7,
            7,
            42
        ],
        [
            7,
            8,
            32
        ],
        [
            7,
            9,
            37
        ],
        [
            7,
            10,
            46
        ],
        [
            7,
            11,
            35
        ],
        [
            8,
            0,
            41
        ],
        [
            8,
            1,
            62
        ],
        [
            8,
            2,
            42
        ],
        [
            8,
            3,
            26
        ],
        [
            8,
            4,
            27
        ],
        [
            8,
            5,
            37
        ],
        [
            8,
            6,
            39
        ],
        [
            8,
            7,
            39
        ],
        [
            8,
            8,
            35
        ],
        [
            8,
            9,
            28
        ]
    ],
    "issuedata": [
        [
            0,
            0,
            22
        ],
        [
            0,
            1,
            47
        ],
        [
            0,
            2,
            44
        ],
        [
            0,
            3,
            67
        ],
        [
            0,
            4,
            125
        ],
        [
            0,
            5,
            133
        ],
        [
            0,
            6,
            83
        ],
        [
            0,
            7,
            143
        ],
        [
            0,
            8,
            154
        ],
        [
            0,
            9,
            154
        ],
        [
            0,
            10,
            194
        ],
        [
            0,
            11,
            231
        ],
        [
            1,
            0,
            224
        ],
        [
            1,
            1,
            286
        ],
        [
            1,
            2,
            344
        ],
        [
            1,
            3,
            302
        ],
        [
            1,
            4,
            355
        ],
        [
            1,
            5,
            325
        ],
        [
            1,
            6,
            416
        ],
        [
            1,
            7,
            345
        ],
        [
            1,
            8,
            424
        ],
        [
            1,
            9,
            460
        ],
        [
            1,
            10,
            396
        ],
        [
            1,
            11,
            254
        ],
        [
            2,
            0,
            323
        ],
        [
            2,
            1,
            282
        ],
        [
            2,
            2,
            246
        ],
        [
            2,
            3,
            210
        ],
        [
            2,
            4,
            285
        ],
        [
            2,
            5,
            254
        ],
        [
            2,
            6,
            259
        ],
        [
            2,
            7,
            219
        ],
        [
            2,
            8,
            203
        ],
        [
            2,
            9,
            267
        ],
        [
            2,
            10,
            211
        ],
        [
            2,
            11,
            164
        ],
        [
            3,
            0,
            175
        ],
        [
            3,
            1,
            160
        ],
        [
            3,
            2,
            156
        ],
        [
            3,
            3,
            137
        ],
        [
            3,
            4,
            150
        ],
        [
            3,
            5,
            151
        ],
        [
            3,
            6,
            137
        ],
        [
            3,
            7,
            134
        ],
        [
            3,
            8,
            128
        ],
        [
            3,
            9,
            136
        ],
        [
            3,
            10,
            121
        ],
        [
            3,
            11,
            115
        ],
        [
            4,
            0,
            125
        ],
        [
            4,
            1,
            155
        ],
        [
            4,
            2,
            150
        ],
        [
            4,
            3,
            135
        ],
        [
            4,
            4,
            145
        ],
        [
            4,
            5,
            133
        ],
        [
            4,
            6,
            164
        ],
        [
            4,
            7,
            147
        ],
        [
            4,
            8,
            121
        ],
        [
            4,
            9,
            102
        ],
        [
            4,
            10,
            95
        ],
        [
            4,
            11,
            78
        ],
        [
            5,
            0,
            96
        ],
        [
            5,
            1,
            117
        ],
        [
            5,
            2,
            116
        ],
        [
            5,
            3,
            88
        ],
        [
            5,
            4,
            98
        ],
        [
            5,
            5,
            111
        ],
        [
            5,
            6,
            78
        ],
        [
            5,
            7,
            61
        ],
        [
            5,
            8,
            83
        ],
        [
            5,
            9,
            74
        ],
        [
            5,
            10,
            77
        ],
        [
            5,
            11,
            58
        ],
        [
            6,
            0,
            65
        ],
        [
            6,
            1,
            54
        ],
        [
            6,
            2,
            57
        ],
        [
            6,
            3,
            40
        ],
        [
            6,
            4,
            51
        ],
        [
            6,
            5,
            56
        ],
        [
            6,
            6,
            59
        ],
        [
            6,
            7,
            58
        ],
        [
            6,
            8,
            59
        ],
        [
            6,
            9,
            61
        ],
        [
            6,
            10,
            104
        ],
        [
            6,
            11,
            113
        ],
        [
            7,
            0,
            111
        ],
        [
            7,
            1,
            98
        ],
        [
            7,
            2,
            71
        ],
        [
            7,
            3,
            62
        ],
        [
            7,
            4,
            81
        ],
        [
            7,
            5,
            81
        ],
        [
            7,
            6,
            66
        ],
        [
            7,
            7,
            69
        ],
        [
            7,
            8,
            57
        ],
        [
            7,
            9,
            55
        ],
        [
            7,
            10,
            64
        ],
        [
            7,
            11,
            50
        ],
        [
            8,
            0,
            62
        ],
        [
            8,
            1,
            58
        ],
        [
            8,
            2,
            54
        ],
        [
            8,
            3,
            88
        ],
        [
            8,
            4,
            88
        ],
        [
            8,
            5,
            66
        ],
        [
            8,
            6,
            71
        ],
        [
            8,
            7,
            55
        ],
        [
            8,
            8,
            49
        ],
        [
            8,
            9,
            58
        ]
    ]
}
        };
    },
    mounted() {
    },
    computed: {
        ...mapState(['currentRepository'])
    },
    methods: {
        async fetchData(path) {
            const datePattern = /^\d{4}-(0[1-9]|1[0-2])$/;
            const filterData = (datas) => {
                let filteredDatas = {};
                for (const key in datas) {
                    if (datePattern.test(key)) {
                        filteredDatas[key] = datas[key];
                    }
                }
                return filteredDatas;
            }
            let starResponse = await axios.get(path + '/stars.json');
            let starData = await starResponse.data;
            starData = filterData(starData);
            let forkResponse = await axios.get(path + '/technical_fork.json');
            let forkData = await forkResponse.data;
            forkData = filterData(forkData);
            let issueResponse = await axios.get(path + '/issues_new.json');
            let issueData = await issueResponse.data;
            issueData = filterData(issueData);

            // 获取所有的键
            let starKeys = Object.keys(starData);
            let forkKeys = Object.keys(forkData);
            let issueKeys = Object.keys(issueData);

            // 找出公共的键
            let commonKeys = starKeys.filter(value => forkKeys.includes(value) && issueKeys.includes(value));
            let firstyear = parseInt(commonKeys[0].split('-')[0]);
            let data = {
                months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
                year: [...new Set(commonKeys.map(key => key.split('-')[0]))],
                stardata: commonKeys.map((key) => {
                    const monthIndex = parseInt(key.split('-')[1]) - 1; // 获取月份索引 (0-11)
                    const yearIndex = parseInt(key.split('-')[0]) - firstyear; // 获取相对于第一年的年份索引
                    const value = starData[key];
                    return [yearIndex, monthIndex, value]; // 转换为 [年份索引, 月份索引, 值] 格式
                }),
                forkdata: commonKeys.map((key) => {
                    const monthIndex = parseInt(key.split('-')[1]) - 1; 
                    const yearIndex = parseInt(key.split('-')[0]) - firstyear; 
                    const value = forkData[key];
                    return [yearIndex, monthIndex, value]; 
                }),
                issuedata: commonKeys.map((key) => {
                    const monthIndex = parseInt(key.split('-')[1]) - 1; 
                    const yearIndex = parseInt(key.split('-')[0]) - firstyear; 
                    const value = issueData[key];
                    return [yearIndex, monthIndex, value];
                }),
                
            }
            return data
        }
    },
    watch: {
        currentRepository: {
            handler: async function (newVal) {
                this.chartData = await this.fetchData('https://oss.x-lab.info/open_digger/github/' + newVal);
            },
            deep: true

        }
    }
}
</script>